# Generated by Django 4.2.3 on 2023-10-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="time_limit",
        ),
        migrations.AlterField(
            model_name="question",
            name="correct",
            field=models.BooleanField(
                default=False, help_text="Leave empty if in creation."
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="duration",
            field=models.DurationField(help_text="Time limit to complete the test"),
        ),
        migrations.AlterField(
            model_name="test",
            name="summary",
            field=models.TextField(
                help_text="Enter a brief description of the Test.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="total_score",
            field=models.PositiveIntegerField(
                help_text="Total marks or score for the test. Set to zero if not attempted."
            ),
        ),
    ]
